'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    return queryInterface.bulkInsert('products', [
      {
        product_id: 1,
        productName: 'Bodrex',
        productPrice: 20000,
        productImage: '/public/productImages/1.jpg',
        productStock: 23,
        description: 'Bodrex',
        packageType: 'Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 2,
        productName: 'Paramex',
        productPrice: 10000,
        productImage: '/public/productImages/2.jpg',
        productStock: 45,
        description: 'Paramex',
        packageType: 'Botol',
        servingType: 'Tablet',

        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 3,
        productName: 'Salonpas',
        productPrice: 4000,
        productImage: '/public/productImages/3.png',
        productStock: 96,
        description: 'Salonpas',
        packageType: 'Strip',
        servingType: 'Lembaran',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 4,
        productName: 'Vitamin B1 50 mg 10 tablet',
        productPrice: 1300,
        description: 'Product desc4',
        productStock: 23,
        productImage: '/public/productImages/4.png',
        packageType: 'Per Strip',
        servingType: 'Kapsul',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 5,
        productName: 'Vitamin C 100 mg 10 Tablet',
        productPrice: 1000,
        description: 'Product desc5',
        productStock: 23,
        productImage: '/public/productImages/5.png',
        packageType: 'Per Strip',
        servingType: 'Kapsul',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 6,
        productName: 'Vitamin B12 IPI 45 Tablet',
        productPrice: 5100,
        description: 'Product desc6',
        productStock: 23,
        productImage: '/public/productImages/6.png',
        packageType: 'Per Botol',
        servingType: 'Kapsul',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 7,
        productName: 'Blackmores Vitamin C 500  mg 60 Tablet',
        productPrice: 109800,
        description: 'Product desc7',
        productStock: 23,
        productImage: '/public/productImages/7.png',
        packageType: 'Per Botol',
        servingType: 'Kapsul',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 8,
        productName: 'Vitamin A IPI 45 Tablet',
        productPrice: 3700,
        description: 'Product desc8',
        productStock: 23,
        productImage: '/public/productImages/8.png',
        packageType: 'Per Botol',
        servingType: 'Kapsul',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 9,
        productName: 'Enervon C',
        productPrice: 15000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/9.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 10,
        productName: 'Zegavit 5 Kaplet',
        productPrice: 23500,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/10.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 11,
        productName: 'Prove D3-1000 IU 10 Tablet',
        productPrice: 29000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/11.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 12,
        productName: 'Hi-D 5000 Vitamin D3 6 Tablet',
        productPrice: 25000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/12.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 13,
        productName: 'Vitamin C IPI 50 mg 45 Tablet',
        productPrice: 5000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/13.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 14,
        productName: 'Holisticare Ester C 4 Tablet',
        productPrice: 6300,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/14.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 15,
        productName: 'Sido Muncul Natural Vitamin E 100 IU 50 Soft Capsule',
        productPrice: 83000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/15.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 16,
        productName: 'Redoxon Vitamin C 2 Tablet',
        productPrice: 2800,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/16.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        product_id: 17,
        productName: 'Golden Bear Vitamin C + Quercetin 30 Tablet',
        productPrice: 14000,
        description: 'Product desc',
        productStock: 12,
        productImage: '/public/productImages/17.png',
        packageType: 'Per Strip',
        servingType: 'tablet',
        isPublic: true,
        defaultQuantity: 20,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  async down(queryInterface, Sequelize) {
    return queryInterface.bulkDelete('products', null, {});
  },
};
